stages:
  - build
  - package

build de l'application:
  stage: build
  image: node:22
  cache:
    key:
      files:
        - package.json
        - package-lock.json
    paths:
      - ./.npm/
  script:
    - npm ci npm ci --cache .npm --prefer-offline
    - npm run build --production
  artifacts:
    paths:
      - dist/

create image:
  stage: package
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA ./
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

